workers_dev = true
name = "pilot-landing-page"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"

[observability.logs]
enabled = true

[assets]
directory = './build/client'
binding = "ASSETS"

[placement]
mode = "smart"
